trigger:
- master
variables: 
  taskSourceFolder: .\src
  taskFolder: .\
stages:  
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted VS2017
      demands:
      - msbuild
    steps:
    - powershell: 
        npm install
      workingDirectory: $(taskSourceFolder)
      displayName: 'npm install'
    - powershell: 
        Rename-Item -Path "$(taskSourceFolder)\task.$(version)" -NewName "task.json"
      displayName: 'specify task.json'
    # - powershell: 
    #     tsc
    #   workingDirectory: $(taskSourceFolder)
    #   displayName: 'compile'
    - powershell:
        npm test
      workingDirectory: $(taskSourceFolder)
      displayName: 'test'  
    - task: PRInsights@0
      displayName: Pull Request Insights
    - task: TfxInstaller@1
      inputs:
        version: 'v0.6.x'
    # - powershell:
    #     Remove-Item './node_modules/fileset/test/fixtures/an (odd) filename.js' –recurse 
    #   workingDirectory: $(taskSourceFolder)
    #   displayName: 'Remove Bad Node File'
    # - task: PackageVSTSExtension@1
    #   inputs:
    #     rootFolder: "./"
    #     patternManifest: "vss-extension-$(version).json"
    #     outputPath: "./epsteam.PullRequestInsightsExtension.vsix"
    #   displayName: Package Task
    - powershell:
        npm run build$(version) 
      workingDirectory: $(taskFolder)
      displayName: 'Run build'
    - task: PublishExtension@1
      inputs:
        connectTo: "VsTeam"
        connectedServiceName: "Visual Studio Marketplace"
        fileType: "vsix"
        vsixFile: "./epsteam.PullRequestInsightsExtension.vsix"
        rootFolder: taskFolder
        patternManifest: "vss-extension-$(version).json"
      displayName: Publish Task
  
      
          
